#include "HGamAnalysisFramework/HGamVariables.h"

namespace var {
  HG::pT_h1 pT_h1;
  HG::pT_h2 pT_h2;
  HG::y_h1 y_h1;
  HG::y_h2 y_h2;
  HG::m_h1 m_h1;
  HG::m_h2 m_h2;
  HG::yAbs_yy yAbs_yy;
  HG::pTt_yy pTt_yy;
  HG::m_yy m_yy;
  HG::pT_yy pT_yy;
  HG::pT_y1 pT_y1;
  HG::pT_y2 pT_y2;
  HG::cosTS_yy cosTS_yy;
  HG::phiStar_yy phiStar_yy;
  HG::Dphi_y_y Dphi_y_y;
  HG::Dy_y_y Dy_y_y;
  HG::Njets Njets;
  HG::pT_j1 pT_j1;
  HG::pT_j2 pT_j2;
  HG::yAbs_j1 yAbs_j1;
  HG::yAbs_j2 yAbs_j2;
  HG::pT_yyj pT_yyj;
  HG::m_yyj m_yyj;
  HG::m_jj m_jj;
  HG::Dy_j_j Dy_j_j;
  HG::Dy_yy_jj Dy_yy_jj;
  HG::Dphi_j_j Dphi_j_j;
  HG::Dphi_yy_jj Dphi_yy_jj;
  HG::m_yyjj m_yyjj;
  HG::pT_yyjj pT_yyjj;
  HG::Zepp Zepp;

  HG::isPassedBasic isPassedBasic;
  HG::isPassed isPassed;
  HG::isPassedEventClean isPassedEventClean;
  HG::isFiducial isFiducial;
  HG::isFiducialKinOnly isFiducialKinOnly;
  HG::isDalitzEvent isDalitzEvent;
  HG::cutFlow cutFlow;
  HG::weightInitial weightInitial;
  HG::weight weight;
  HG::weightCategory weightCategory;
  HG::category category;
  HG::numberOfPrimaryVertices numberOfPrimaryVertices;
  HG::selectedVertexZ selectedVertexZ;
  HG::hardestVertexZ hardestVertexZ;
  HG::truthVertexZ truthVertexZ;
  HG::eventShapeDensity eventShapeDensity;
  HG::mu mu;
}
